# Formato de almacenamiento. Cambiarlo puede invalidar datos existentes.
drugsFile: "drugs.yml"

# Extension del archivo de almacenamiento. Cambiarla puede invalidar datos existentes.
fileType: "YAML"

# Si se activa, "drugsFile" se interpreta como un directorio y cada archivo como una droga distinta.

multiFile: false

# Configuracion de sobredosis y caducidad de las drogas.
overdose:
  expire: 120 # Tiempo de caducidad de la droga
  effects:
    nausa: # ID
      type: "NAUSEA" # Tipo de efecto de pocion
      duration: 30 # Duracion del efecto
      amplifier: 1 # Nivel del efecto
      required: 5 # Se aplica cuando el contador alcanza este valor
    weak:
      type: "WEAKNESS"
      duration: 30
      amplifier: 1
      required: 10
