# Formato de almacenamiento (mejor no tocar)
drugsFile: "drugs.yml"

# Extensión del fichero de datos (mejor no tocar)
fileType: "YAML"

# Si se activa, "drugsFile" se trata como una carpeta y cada uno de sus 8 ficheros como una sustancia distinta

multiFile: false

# Ajustes de las sustancias: efectos por abusar de ellas y caducidad
overdose:
  expire: 120 # Cuánto tarda en pasarse
  effects:
    nausa: # ID
      type: "CONFUSION" # Tipo de efecto de poción
      duration: 30 # Cuánto dura el efecto
      amplifier: 1 # Nivel del efecto
      required: 5 # A partir de este nivel del contador, se aplica el efecto
    weak:
      type: "WEAKNESS"
      duration: 30
      amplifier: 1
      required: 10
